---
sudo: required

env:
  - distribution: centos
    version: 7
  - distribution: fedora
    version: 29
  - distribution: fedora
    version: 28
  - distribution: ubuntu
    version: bionic
  - distribution: ubuntu
    version: xenial
  - distribution: debian
    version: jessie

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - ./run-script.sh
