---
- hosts: local
  remote_user: root
  tasks:
  - name: test hostname
    debug:
      msg: "{{ ansible_hostname }}"
  - name: test os dist
    debug:
      msg: "{{ ansible_distribution }} {{ ansible_distribution_release }}"
  - name: install nginx
    include: "{{ item }}"
    with_items:
    - "tasks/nginx.yml"
    

