---
#- hosts: pool
#  remote_user: root
#  vars:
#  - mariadb_root_passwd: my-mariadb-passwd
#  tasks: 
  - name: get variables
    include_vars: "mysql-{{ ansible_distribution }}.yml"
  - name: check if config file esixts
    stat:
      path: /root/.my.cnf
    register: my_cnf
#  - name: test
#    debug:
#      msg: "{{ my_cnf.stat.exists == true }}"
  - name: install or update to latest version of mariadb
    package:
      name: "{{ deps }}"
      state: latest
  - name: copy .my.cnf
    copy:
      src: ./config/.my.cnf
      dest: /root/.my.cnf
      owner: root
      mode: 0600
    when: my_cnf.stat.exists == false
  - name: Start the MySQL service
    service: 
      name: mariadb 
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    mysql_user: 
      name: root 
      host: "{{ item }}" 
      password: "{{ mariadb_root_passwd }}" 
      priv: "*.*:ALL,GRANT"
    with_items:
    - "{{ ansible_fqdn }}"
    - 127.0.0.1
    - ::1
    - localhost 
  - name: update password in config file
    lineinfile:
      path: /root/.my.cnf
      regexp: "^password="
      line: "password={{ mariadb_root_passwd }}"


