---
#- hosts: pool
#  remote_user: root
#  tasks: 
  - name: setup epel-repo
    package:
      name: epel-release
      state: latest
    when: ansible_distribution == "CentOS"
  - name: install or update to latest version of nginx
    package:
      name: nginx
      state: latest
#  - name: copy nginx config files
#    copy:
#      src: ./config/nginx/nginx.conf
#      dest: /etc/nginx/nginx.conf
  - name: test nginx config and restart nginx
    command: nginx -c /etc/nginx/nginx.conf
    changed_when: false
    notify: 
#      - stop nginx
      - restart nginx
#  - name: ensure nginx is running and enabled
#    service:
#      name: nginx
#      enabled: yes
#      state: restarted
#    changed_when: false
#  handlers:
#  - name: restart nginx
#    service:
#      name: nginx
#      state: restarted
